# Generated by Django 4.2.5 on 2023-10-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_guestscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestscore',
            name='book_quote',
        ),
    ]
