# Generated by Django 4.2.5 on 2023-10-10 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_remove_guestscore_book_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestscore',
            name='current_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.bookquote'),
        ),
    ]
