# Generated by Django 4.2.5 on 2023-10-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_alter_guestscore_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestscore',
            name='score',
        ),
        migrations.AddField(
            model_name='guestscore',
            name='scores',
            field=models.TextField(default='[0]'),
        ),
    ]
