# Generated by Django 4.2.5 on 2023-10-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_remove_guestscore_score_guestscore_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestscore',
            name='scores',
            field=models.TextField(blank=True, null=True),
        ),
    ]
