# Generated by Django 4.2.5 on 2023-11-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_userscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestscore',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userscore',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
