# Generated by Django 4.2.5 on 2023-11-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_savedscores'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedscores',
            name='start_times',
            field=models.TextField(blank=True, null=True),
        ),
    ]
