# Generated by Django 4.2.5 on 2023-11-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_savedscores_start_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestscore',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedscores',
            name='durations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userscore',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
