# Generated by Django 4.2.5 on 2023-11-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_bookquote_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookquote',
            name='cover',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
