# Generated by Django 4.2.5 on 2023-11-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_alter_bookquote_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookquote',
            name='cover',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
