# Generated by Django 4.2.5 on 2023-11-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_remove_bookquote_cover_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookquote',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
