# Generated by Django 4.2.5 on 2023-11-25 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0017_alter_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestscore',
            name='past_quotes',
            field=models.ManyToManyField(blank=True, related_name='guest_scores', to='quotes.bookquote'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='past_quotes',
            field=models.ManyToManyField(blank=True, related_name='user_scores', to='quotes.bookquote'),
        ),
        migrations.AlterField(
            model_name='guestscore',
            name='current_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_guest_score', to='quotes.bookquote'),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='current_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_user_score', to='quotes.bookquote'),
        ),
    ]
