# Generated by Django 4.2.5 on 2023-11-26 00:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0018_guestscore_past_quotes_userscore_past_quotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookquote',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='bookquote',
            name='upvotes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
