# Generated by Django 4.2.5 on 2023-11-26 02:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0019_remove_bookquote_upvotes_bookquote_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookquote',
            name='upvotes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
